### ISSUE TITLE
Fork from (external) member and PR is running on wrong / invalid security context

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/org#14]
e.g. access to source repo gh action secrets not possible.

**Comment by MarkusTiede** [comment]
resolved with #11

**Comment by MarkusTiede** [comment]
Maybe check with @NicoleTiede.

**Comment by christiansiegel** [comment]
successfuly ested in incubator via PR from fork:
- `verify-org-config` workflow ✅ 
- `verify-branch-author-email` workflow ✅  (altough the run needs to be approved by a reviewer first. IMO that's ok for now)

![2021-05-05 10_49_50-added kamrwo to group members by kamrwo · Pull Request #46 · baloise-incubator_o](https://user-images.githubusercontent.com/13996624/117119127-ec39b480-ad91-11eb-9ffb-510f269dcc85.png)
