### ISSUE TITLE
Add Jelena Djindjic 

### ISSUE THREAD

**Issue by hirsch88** [baloise/org#15]
Jelena Djindjic will help working on our OpenSource projects

**Comment by JelenaSretenovic** [comment]
## For new organization members
### I acknowledge that
- [x] I have **read and understood the [Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/)**
- [x] I agree to **act accordingly (with due dilligence) to our guidelines**
- [x] I have **no open questions** regarding the topics covered

**Comment by hirsch88** [comment]
Created PR =>  https://github.com/baloise/org/pull/16
