### ISSUE TITLE
Unify group responsibility for administration tasks

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/org#29]
I'd like to propose to unify the group responsible for administration tasks such as:
- [Organization ownership](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/permission-levels-for-an-organization#permission-levels-for-an-organization)
- Read and Write access to our mailbox: Group.CH_Open-Source@baloise.ch
- Read and Write access to all [technical account(s) & profiles](https://github.com/baloise/open-source/blob/master/docs/md/activities/profiles.md)

I'd like to have this clear and unified for both of our organizations "baloise" and "baloise-incubator".

I'd like to propose the "CoP Open-Source" team member's to be 1:1 this group.

**Comment by MarkusTiede** [comment]
Links to https://github.com/baloise/open-source/issues/307

**Comment by joachimprinzbach** [comment]
@kullmanp incubator and main org aligned.
